"""Screensaver photo storage.

Uploads are the only place this app accepts a file from a user, so the rules are
strict and deliberately not negotiable by the client:

* the format is decided by decoding the image, never by the declared Content-Type
  or the file extension -- both are attacker-controlled;
* every image is re-encoded, which drops EXIF (including GPS coordinates on phone
  photos) and guarantees the bytes on disk are a real image and not a polyglot;
* stored filenames are generated here, so no user input ever reaches a filesystem
  path and traversal is structurally impossible rather than filtered out.
"""

import io
import secrets
from pathlib import Path

from PIL import Image, UnidentifiedImageError

# Pillow will happily open a "decompression bomb" -- a small file that expands to
# gigabytes of pixels. Cap it well below the default warning threshold.
Image.MAX_IMAGE_PIXELS = 64_000_000

MAX_UPLOAD_BYTES = 12 * 1024 * 1024
MAX_LIBRARY_BYTES = 2 * 1024 * 1024 * 1024
MAX_DIMENSION = 2560  # plenty for any wall display; keeps files small
JPEG_QUALITY = 86

ALLOWED_FORMATS = {"JPEG", "PNG", "WEBP", "GIF", "HEIF", "MPO"}


class PhotoError(ValueError):
    """Rejected upload. The message is safe to show the user."""


def photo_dir() -> Path:
    """Photos live beside the database inside the data volume, so the documented
    backup covers them without a second step."""
    from ..config import get_settings

    url = get_settings().database_url
    if url.startswith("sqlite"):
        db_path = url.split("///", 1)[-1]
        base = Path(db_path).parent if db_path and db_path != ":memory:" else Path("/data")
    else:
        base = Path("/data")
    target = base / "photos"
    target.mkdir(parents=True, exist_ok=True)
    return target


def library_bytes() -> int:
    return sum(f.stat().st_size for f in photo_dir().glob("*") if f.is_file())


def store(raw: bytes, original_name: str | None) -> dict:
    """Validate, normalise and write an uploaded image. Returns the row fields."""
    if not raw:
        raise PhotoError("The uploaded file was empty.")
    if len(raw) > MAX_UPLOAD_BYTES:
        raise PhotoError(
            f"That image is larger than {MAX_UPLOAD_BYTES // (1024 * 1024)} MB."
        )
    if library_bytes() + len(raw) > MAX_LIBRARY_BYTES:
        raise PhotoError("The photo library is full. Delete some photos first.")

    try:
        with Image.open(io.BytesIO(raw)) as probe:
            fmt = (probe.format or "").upper()
            probe.verify()  # structural check; consumes the file object
    except (UnidentifiedImageError, OSError, Image.DecompressionBombError) as exc:
        raise PhotoError("That file isn't an image we can read.") from exc

    if fmt not in ALLOWED_FORMATS:
        raise PhotoError(f"{fmt or 'That format'} isn't supported. Use JPEG, PNG or WebP.")

    # verify() leaves the image unusable, so reopen to actually transform it.
    try:
        with Image.open(io.BytesIO(raw)) as img:
            img = img.convert("RGB")
            img.thumbnail((MAX_DIMENSION, MAX_DIMENSION), Image.LANCZOS)
            width, height = img.size
            buf = io.BytesIO()
            img.save(buf, format="JPEG", quality=JPEG_QUALITY, optimize=True)
    except (OSError, Image.DecompressionBombError) as exc:
        raise PhotoError("That image couldn't be processed.") from exc

    data = buf.getvalue()
    filename = f"{secrets.token_hex(16)}.jpg"
    (photo_dir() / filename).write_bytes(data)

    return {
        "filename": filename,
        "original_name": (original_name or "")[:255] or None,
        "content_type": "image/jpeg",
        "size_bytes": len(data),
        "width": width,
        "height": height,
    }


def path_for(filename: str) -> Path:
    """Resolve a stored filename to a path, refusing anything that escapes the
    photo directory. Filenames are generated by `store`, so this can only trip on
    a corrupted row or a hand-edited database -- but it is the last line before a
    file read, so it checks anyway."""
    base = photo_dir().resolve()
    target = (base / filename).resolve()
    if target.parent != base or not target.is_file():
        raise PhotoError("Photo not found.")
    return target


def delete_file(filename: str) -> None:
    try:
        path_for(filename).unlink()
    except (PhotoError, OSError):
        pass  # the row goes regardless; a missing file is not an error worth raising
